### ISSUE TITLE
Use of '\verb<space>foo<space>' breaks under some setups (e.g., MikTeX on W10 via Git bash)

### ISSUE THREAD

**Issue by marcoxa** [JuliaCon/JuliaConSubmission.jl#21]
Hi

subject says it all.  Just change the instances of
```
\verb foo  and so on...
```
in `paper.tex`, with something like
```
\verb|foo| and so on...
```
and everything is hunky-dory.

All the best

Marco

**Comment by jorgepz** [comment]
`\verb foo` does not work for me neither, using texlive in ArchLinux. I proposed the changes in PR #22 
Jorge
