### ISSUE TITLE
last line of Abstract looks out of place

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaCon/JuliaConSubmission.jl#4]
```
Abstract

This paper offers a new perspective on the antics of that quick brown fox,
that they serve to mitigate canine lassitude and encourage cow jumping.
    Proceedings of JuliaCon

```

**Comment by matbesancon** [comment]
The abstract I have is:
```
This is a guide for authors who are preparing papers for JuliaCon using the \LaTeX{} document
preparation system and the \verb juliacon  class file.
```

Where do you see this brown fox thing?

**Comment by JeffreySarnoff** [comment]
so you see one way that tedium becomes less tedious for me
Its not in your master doc -- simply present to show how 
   `Proceedings of JuliaCon`

which does print -- looks out of place
(it needs to be removed or to be separated by ?3/4 line and have the year)

**Comment by matbesancon** [comment]
Oh I see, just fixed it thanks!

**Comment by matbesancon** [comment]
Should be good now, which others did you mean?

**Comment by JeffreySarnoff** [comment]
at the top of the initial page of a submission to the proceedings, just above the submission's title

![image](https://user-images.githubusercontent.com/1682118/57406775-9edcd980-71af-11e9-808d-7ddc4eac0ce4.png)

**Comment by matbesancon** [comment]
Ah thanks. This one was on purpose but it does look a bit weird. Just removed it in last commit
