### ISSUE TITLE
Using biblatex instead of bibtex

### ISSUE THREAD

**Issue by Nosferican** [JuliaCon/JuliaConSubmission.jl#7]
Proposal:

**biblatex** is the preferred bibliography management in LaTeX and uses biber over bibtex as the backend. In terms of actual output changes, it would be nice to include the DOI which I think it is an improvement over the current output.

- Add to `cls`,
```
\usepackage[maxbibnames=99,
            ]{biblatex}
\addbibresource{ref.bib}
```
- Delete `juliacon.bst`, `bib.tex`, and `\input{bib.tex}` in `paper.tex`

**Comment by matbesancon** [comment]
> biblatex is the preferred bibliography management in LaTeX and uses biber over bibtex as the backend

Not sure about this, and not sure that biblatex is supported as broadly as bibtex on all systems, including the JOSS build system which we copied and use for this build pipeline

> In terms of actual output changes, it would be nice to include the DOI which I think it is an improvement over the current output.

Not sure what you mean? Include the DOI where, they are already included aren't they?

**Comment by Nosferican** [comment]
While biber is certainly more powerful and flexible, there might be cases such as journals that haven't updated their templates or pipelines which could restrict use to only bibtex. That is a very valid argument. Might be worth to check with JOSS on that particular.

The issue with the current bibliographic settings is that an entry with a DOI will not display the DOI. For example, taking the Overleaf project make the following changes,
On `ref.bib`, instead of the url entry with a DOI, specify the doi directly.
```
@article{Moore1990,
	author = {Moore, James T. and Bard, Jonathan F.},
	doi = {10.1287/opre.38.5.911},
	issn = {0030-364X},
	journal = {Operations Research},
	keywords = {games: noncooperative,integer: branch-and-bound algorithms,programming},
	mendeley-groups = {bilevel - hierarchical},
	month = {oct},
	number = {5},
	pages = {911--921},
	publisher = { INFORMS },
	title = {{The Mixed Integer Linear Bilevel Programming Problem}},
	doi = {10.1287/opre.38.5.911},
	volume = {38},
	year = {1990}
}
```
On `paper.tex`, cite Moore1990 (line 522),
```
\cite{bezanson2017julia,Moore1990}
```
The resulting bibliography is,

James  T.  Moore  and  Jonathan  F.  Bard. The Mixed Integer Linear Bilevel Programming  Problem. Operations Research, 38(5):911–921, oct 1990.

without any displayed DOI. If keeping bibtex, it would just require to change the `juliacon.bst` to handle DOI.

**Comment by matbesancon** [comment]
> If keeping bibtex, it would just require to change the juliacon.bst to handle DOI.

I think this would be the preferred option for now (least breaking now that the submission template is already used and the pipeline built). Could you make a PR for it? It would be awesome

**Comment by Nosferican** [comment]
😢I haven't use bibtex in ages so my `bst` is quite limited. I can take a look at it, but it has been a long time since I transitioned to BibLaTeX which use `.bbx`/`.cbx` instead of `bst` for formatting.

**Comment by Nosferican** [comment]
I use author-date in my discipline, but I believe `citet` (textual citation) is compatible with numeric bibliographic style, no? Something like
> Eistein (1905) found x and y.

or
> Eistein [1] found x and y.

I am adapting my paper from `citep` (parenthetical citation) to `cite` (numeric), but wasn't sure on the `citet` to `cite`. Currently it just generates (no author information passed)
> [1] found x and y.

**Comment by Nosferican** [comment]
> least breaking now that the submission template is already used and the pipeline built

Just ran `prep.rb` with biblatex to see if something would break, but everything just works.

**Comment by matbesancon** [comment]
> I am adapting my paper from citep (parenthetical citation) to cite (numeric), but wasn't sure on the citet to cite. Currently it just generates (no author information passed)
    [1] found x and y.

Yes, that's IEEE citation format, which is rather common for CS proceedings.

> Just ran prep.rb with biblatex to see if something would break, but everything just works.

Yes prep.rb is just a way to make builds work locally, the real way the paper is built is à la JOSS, so the same logic is ported in a pipeline running on github, same behaviour not guaranteed
