### ISSUE TITLE
PDF Metadata

### ISSUE THREAD

**Issue by Nosferican** [JuliaCon/JuliaConSubmission.jl#8]
I played around with the template locally and noticed that the PDF metadata wasn't embedded in the code. I ended up using something à la
```
\hypersetup{
pdftitle = {Econometrics.jl},
pdfsubject = {JuliaCon 2019 Proceedings},
pdfauthor = {José Bayoán Santiago Calderón},
pdfkeywords = {Julia, Econometrics, Statistical Software, Software Validation}
}
```
I don't know if someone wants to make a PR to pre-fill those values from the YAML file.

**Comment by matbesancon** [comment]
I can take a look at this, this should be easily done in the Ruby script.

**Comment by matbesancon** [comment]
@arfon I can make a PR for this but will this not mess up the build pipeline?

**Comment by TheCedarPrince** [comment]
@matbesancon and co, I am a bit confused on this build pipeline as I installed ruby as a separate dependency and running `latexmk -bibtex -c paper.tex` does not automatically generate my updated header file. Instead, I have to run `ruby prep.rb`. This doesn't feel very clean - am I doing something wrong here? Thanks!

**Comment by matbesancon** [comment]
you shouldn't need this, it should be sufficient to `latexmk -pdf paper.tex`

**Comment by TheCedarPrince** [comment]
Hm. Yea, that does not work for me. This may be a separate issue but I am curious as to what is happening @matbesancon . Shall we continue this in a separate issue?
